#!/bin/bash

set -e
set -o pipefail

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

# Read inputs
source=$1
payload=$(mktemp kubectl-resource-request.XXXXXX)
cat > $payload <&0

export CONCOURSE=true
export DANGER_GITHUB_API_TOKEN=$(jq -r '.source.github_api_token // ""' < $payload)
export DANGER_GITHUB_HOST=$(jq -r '.source.github_host // "github.com"' < $payload)
export DANGER_GITHUB_API_BASE_URL=$(jq -r '.source.github_api_base_url // "https://api.github.com"' < $payload)
export REPO_SLUG=$(jq -r '.source.repo_slug // ""' < $payload)

workdir=$(jq -r '.params.workdir // "dangerfile.js"' < $payload)
dangerfile=$(jq -r '.params.dangerfile // "dangerfile.js"' < $payload)
package_json=$(jq -r '.params.package_json' // "" < $payload)

cd $source/$workdir

export PULL_REQUEST_ID=$(git config --get pullrequest.id)
pr_head_ref=$(git rev-parse HEAD)

if [ -n "$package_json" ]; then
  cp $package_json ./package.json
  npm install
fi

danger ci -d $dangerfile

echo '{ "ref" "", "version": {"pr":""} }' | \
        jq --arg REF "$pr_head_ref" '.ref = $REF' | \
        jq --arg PR "$PULL_REQUEST_ID" '.version.pr = $PR' >&3
